/// Flutter icons InTimeIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InTimeIcons
///      fonts:
///       - asset: fonts/InTimeIcons.ttf
///
/// 
///
import 'package:flutter_web/widgets.dart';

class InTimeIcons {
  InTimeIcons._();

  static const _kFontFam = 'InTimeIcons';

  static const IconData ios_globe = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ios_bed = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ios_alarm = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ios_stopwatch = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ios_timer = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ios_key = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ios_mail = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData ios_calculator = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData ios_arrow_back = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData calculator = const IconData(0xe80a, fontFamily: _kFontFam);
}
